export default {
  "story.community.title": "Community Conservation",
  "story.community.p1":
    "Since our first visit to Sudian Lisu Township in June 2018 for school-based gibbon-conservation outreach activities, through a baseline community survey in 2019, to the 2023 expansion of community-based conservation projects in Lishu and Lamahe community, we have spent five years walking with Lisu community members to discover what true community-based conservation for the Skywalker hoolock gibbon might look like. The saplings planted for habitat restoration are still only young shoots, and the canopy bridges across cardamom fields remain, for now, untouched by gibbons. These efforts need time to flourish—but perhaps the most striking change is in the people themselves, whose own journey of conservation has already begun.",
  "story.community.p2":
    "In the Lishu and Lamahe community-based conservation project, a key strategy for mobilization is the Eco-Public Affairs Fund, which encourages community self-organization and supports conservation leadership. We work mainly with women's groups. Each year, ahead of International Women's Day, the community and Cloud Mountain Conservation discuss and agree on that year's conservation actions—habitat restoration, rope-bridge installation, and more. These plans then circulate through several rounds of community discussion to set timelines, refine details, and decide the amount of collective-labor point—known as \"工\"—required. The total number of collective-labor point directly determines the Eco-Public Affairs funding Cloud Mountain provides. The women's group, as the primary organizer, also manages the fund, channeling it into public projects that strengthen the community's long-term sustainable development.",
  "story.community.p3":
    'The way a community debates and agrees on specific conservation actions is driven by the needs of the Skywalker hoolock gibbon—this is the gibbon-centered side of the project\'s logic. Meanwhile, the way the Eco-Public Affairs Fund is used—mobilizing more people and building wider recognition and participation—reflects the logic of community self-organization. Cloud Mountain Conservation\'s work in local communities aims to connect these two strands, so that community groups themselves lead the conservation effort. The core goal is to dissolve the old divide between "conservation issues" and "community affair." When that divide disappears, and the Eco-Public Affairs Fund is in play, conservation stops feeling like an outside demand. It becomes part of the community\'s own agenda—something discussed and acted on as naturally as any other local concern.',
  "story.community.p4":
    "From a community-sustainability perspective, we organized a peer-learning trip for members of the Lishu community to visit project sites run by three partner organizations. After this trip, the former women's group leader Zao Yanfang approached us with excitement. She shared how inspiring it was to see how women in other places manage their daily lives—it had opened their eyes and energized them. Listening to the women leader speak with such cheer and confidence about the future they imagine was profoundly moving—a quiet joy and reassurance that words can scarcely convey.",
  "story.community.p5":
    "From 2018 to 2023, five years have passed. The people of local communities have begun to imagine an ecotourism future that is both gibbon-friendly and ecologically sustainable. Local communities is changing.",
  "story.community.p6":
    'If we were to measure the success of our community-based conservation projects only by ecological outcomes, the formation of new gibbon families and the birth of infant gibbons could indeed serve as powerful indicators of species recovery. Yet community-based conservation asks us to look beyond numbers. We want to keep the focus on the Lisu ehic minority people who call this land home and to honor their patience and initiative as they embrace the once-unfamiliar idea of "conservation." These very qualities have allowed the project to take root and flourish here.',
};
